name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ruby and Jekyll
        run: sudo apt-get update && sudo apt-get install -y ruby-full build-essential zlib1g-dev

      - name: Install Bundler and Jekyll (User Directory)
        run: |
            gem install --user-install bundler jekyll
            echo 'export GEM_HOME="$HOME/.gem"' >> $GITHUB_ENV
            echo 'export PATH="$HOME/.gem/ruby/3.0.0/bin:$PATH"' >> $GITHUB_ENV
            echo 'export PATH="$HOME/.local/share/gem/ruby/3.0.0/bin:$PATH"' >> $GITHUB_ENV


      - name: Verify Jekyll Installation
        run: |
          echo "Ruby version:"
          ruby -v
          echo "Jekyll version:"
          jekyll -v
          echo "Bundler version:"
          bundle -v

      - name: Install dependencies
        run: bundle install || echo "No Gemfile found, skipping bundle install"

      - name: Build Jekyll Site Manually
        run: bundle exec jekyll build --destination ./_site

      - name: Verify `_site` directory
        run: ls -la ./_site

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./_site


  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2  # No change needed
