name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ruby and Jekyll
        run: sudo apt-get update && sudo apt-get install -y ruby-full build-essential zlib1g-dev

      - name: Install Bundler and Jekyll (User Directory)
        run: |
          gem install --user-install bundler jekyll
          GEM_PATH=$(ruby -e 'puts Gem.user_dir')
          echo "GEM_HOME=$GEM_PATH" >> $GITHUB_ENV
          echo "PATH=$GEM_PATH/bin:$PATH" >> $GITHUB_ENV

      - name: Generate Gemfile (if missing)
        run: |
          if [ ! -f Gemfile ]; then
            echo "source 'https://rubygems.org'" > Gemfile
            echo "gem 'jekyll'" >> Gemfile
          fi

      - name: Install dependencies
        run: $GEM_HOME/bin/bundle install

      - name: Build Jekyll Site
        run: $GEM_HOME/bin/bundle exec jekyll build --destination ${{ github.workspace }}/_site

      - name: Verify `_site` directory
        run: |
          echo "Contents of _site:"
          ls -R ${{ github.workspace }}/_site
          echo "Total files: $(find ${{ github.workspace }}/_site -type f | wc -l)"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ${{ github.workspace }}/_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact (Debugging)
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./_site-debug

      - name: Verify downloaded artifact
        run: |
          echo "Contents of downloaded artifact:"
          ls -R ./_site-debug
          echo "Total files: $(find ./_site-debug -type f | wc -l)"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
